"""Pydantic models — the canonical event contract shared by pipeline and API.

This schema is the single source of truth. The detection pipeline emits events
that validate against `Event`; the API ingests batches of them via `IngestBatch`.
Keeping the contract in one place means a schema change can't silently diverge
between producer (pipeline) and consumer (API).
"""
from __future__ import annotations

from datetime import datetime, timezone
from enum import Enum
from typing import Optional
from uuid import UUID

from pydantic import BaseModel, Field, field_validator, ConfigDict


class EventType(str, Enum):
    ENTRY = "ENTRY"
    EXIT = "EXIT"
    ZONE_ENTER = "ZONE_ENTER"
    ZONE_EXIT = "ZONE_EXIT"
    ZONE_DWELL = "ZONE_DWELL"
    BILLING_QUEUE_JOIN = "BILLING_QUEUE_JOIN"
    BILLING_QUEUE_ABANDON = "BILLING_QUEUE_ABANDON"
    REENTRY = "REENTRY"


# Events that legitimately carry zone_id == null (threshold events).
ZONELESS_EVENTS = {EventType.ENTRY, EventType.EXIT}


class EventMetadata(BaseModel):
    model_config = ConfigDict(extra="allow")  # forward-compatible: keep unknown keys

    queue_depth: Optional[int] = Field(
        default=None, ge=0, description="Queue depth; populated for BILLING_QUEUE_JOIN"
    )
    sku_zone: Optional[str] = Field(
        default=None, description="Zone label from store_layout.json"
    )
    session_seq: int = Field(
        default=0, ge=0, description="Ordinal position of this event within the visitor session"
    )


class Event(BaseModel):
    """A single behavioural event emitted by the detection pipeline."""

    model_config = ConfigDict(use_enum_values=True)

    event_id: UUID = Field(description="Globally unique uuid-v4 generated by the pipeline")
    store_id: str = Field(min_length=1)
    camera_id: str = Field(min_length=1)
    visitor_id: str = Field(min_length=1, description="Re-ID token, unique per visit session")
    event_type: EventType
    timestamp: datetime = Field(description="ISO-8601 UTC")
    zone_id: Optional[str] = None
    dwell_ms: int = Field(default=0, ge=0)
    is_staff: bool = False
    # Do NOT suppress low-confidence events — calibration is scored. Allow full range.
    confidence: float = Field(ge=0.0, le=1.0)
    metadata: EventMetadata = Field(default_factory=EventMetadata)

    @field_validator("timestamp")
    @classmethod
    def _ensure_utc(cls, v: datetime) -> datetime:
        # Normalise everything to timezone-aware UTC so downstream math is unambiguous.
        if v.tzinfo is None:
            return v.replace(tzinfo=timezone.utc)
        return v.astimezone(timezone.utc)

    @field_validator("zone_id")
    @classmethod
    def _zone_consistency(cls, v, info):
        # ENTRY/EXIT may be zoneless; other zone events should name a zone. We warn-by-allow
        # rather than reject, because rejecting valid-but-incomplete detections loses recall.
        return v


class IngestBatch(BaseModel):
    """Batch envelope for POST /events/ingest (max 500 events)."""

    events: list[Event] = Field(min_length=1, max_length=500)


class IngestItemError(BaseModel):
    index: int
    event_id: Optional[str] = None
    error: str


class IngestResponse(BaseModel):
    """Partial-success response: malformed items are reported, valid ones are stored."""

    received: int
    accepted: int
    duplicates: int
    rejected: int
    errors: list[IngestItemError] = Field(default_factory=list)
